### ISSUE TITLE
HTTPS issues

### ISSUE THREAD

**Issue by rosano** [67P/waves#18]
https://waves.kosmos.org
> 'The certificate is only valid for *.5apps.com.'

**Comment by raucao** [comment]
Sorry, we had added CAA records for kosmos.org domains, to protect against MitM attacks like the one on jabber.ru recently. But this app is hosted on 5apps Deploy, which didn't have any CAA records set yet.

All sites on Deploy which use CAA records for their domains that are pointed to Deploy via a CNAME will now get their automatic TLS certificates issued without problems again.
